### ISSUE TITLE
Incorrect scaling for VGA modes with "fixed borders"

### ISSUE THREAD

**Issue by pdjstone** [sarah-walker-pcem/arculator#36]
To reproduce, configure Arculator to run an A5000, then select Video > Border size > Fixed (standard monitor) borders. Any VGA mode (e.g. 27, 31) will be scaled incorrectly, like this:

![image](https://github.com/sarah-walker-pcem/arculator/assets/2699275/6148c9d8-faa0-43ab-bb40-9bebae2f1c77)

The "native borders" setting works fine in these modes. Looking at the code in `vidc.c`, I can see the three different branches of code that do scaling differently depending on the border size setting (stored in the `display_mode ` variable). However I'm not too familiar with the various VIDC control registers and how different modes work under the hood, so I'm unsure of the correct behaviour here.

**Comment by sarah-walker-pcem** [comment]
Fixed (standard monitor) borders are for monitor type 0 only.
