### ISSUE TITLE
"Disabled" drive noise is actually just white noise

### ISSUE THREAD

**Issue by IJeffray** [sarah-walker-pcem/arculator#38]
2.2, under Windows 10, Choose "Disc - Disc Drive Noise - Disabled".  Restart arculator or hard-reset the emulated machine and you get white noise on startup.  Clicking a drive icon in RISC OS also gets white noise.  Fully repeatable.

**Comment by Sophira** [comment]
I can confirm this occurs on Linux as well. I was able to bisect the issue down to commit 28bbfdad6987f4af8dd2048bc243fc5a5ebf5183, which is when Arculator switched from using OpenAL for audio to using SDL. It seems like whatever Arculator does for "silence" is the wrong thing for SDL.
